# Generated by Django 5.2.5 on 2025-08-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='cteated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
