# Generated by Django 5.2.5 on 2025-09-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_cteated_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('clothes', 'clothes'), ('books', 'books'), ('electronics', 'electronics')], help_text='select category', max_length=100, null=True),
        ),
    ]
